[font]
size = 12
offset = { x = 0, y = 0 }

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"

[window]
dynamic_padding = true
padding = { x = 0, y = 0 }
decorations = "FULL"
dynamic_title = true

[colors.primary]
background = "#FFFFFF"
foreground = "#000000"

[colors.bright]
black   = "#484848"
red     = "#EE0000"
green   = "#009000"
yellow  = "#EEAA44"
blue    = "#4444FF"
magenta = "#D800D8"
cyan    = "#009898"
white   = "#FFFFFF"

[colors.normal]
black   = "#000000"
red     = "#BB0000"
green   = "#007000"
yellow  = "#AA7722"
blue    = "#0000EE"
magenta = "#C400C4"
cyan    = "#008484"
white   = "#C8C8C8"
