[colors.primary]
background = "#FFFFFF"
foreground = "#000000"

[colors.bright]
black   = "#595959"
red     = "#EE0000"
green   = "#008A00"
yellow  = "#7A7A00"
blue    = "#0000FF"
magenta = "#D100D1"
cyan    = "#008484"
white   = "#FFFFFF"

[colors.normal]
black   = "#000000"
red     = "#B60000"
green   = "#006800"
yellow  = "#5C5C00"
blue    = "#0000FF"
magenta = "#9F009F"
cyan    = "#006363"
white   = "#EEEEEE"
