[colors.bright]
black = '#222222'
blue = '#4C7899'
cyan = '#00CDCD'
green = '#1AC261'
magenta = '#FF00AF'
red = '#ed333b'
white = '#FFFFFF'
yellow = '#FFAF00'

[colors.cursor]
cursor = '#666666'
text = '#FFFFFF'

[colors.normal]
black = '#000000'
blue = '#285577'
cyan = '#04BBB9'
green = '#00B600'
magenta = '#99246F'
red = '#c01c28'
white = '#EEEEEE'
yellow = '#B58B2C'

[colors.primary]
background = '#D7D7D7'
foreground = '#000000'

[colors.selection]
background = '#c0bfbc'
text = '#000000'
